### PR TITLE
Bump Leia to 18.6

### PR DESCRIPTION
**Pull request by hugepants**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by CHBMB** [comment]
https://github.com/linuxserver/docker-kodi-headless/issues/105

**Comment by CHBMB** [comment]
@hugepants Have you built this locally and checked it works?

**Comment by hugepants** [comment]
> 
> 
> @hugepants Have you built this locally and checked it works?

Yes I have built it and it works, I've been running it for a while doing automated library updates. No issues encountered.

**Comment by CHBMB** [comment]
Any interest in maintaining it?  None of the team use it any more?

**Comment by hugepants** [comment]
Sure, I would like to maintain it - where do I sign up?

**Comment by CHBMB** [comment]
Come chat with us on Discord and we'll get it all straightened out.

https://discord.gg/NmuRmT

**Comment by hugepants** [comment]
Closing due to reasons given in https://github.com/linuxserver/docker-kodi-headless/issues/112#issuecomment-604543002

**Pull request closed without merging**
